version: "3.8"

services:
  booking-app:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./booking-app
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./booking-app:/app"
    depends_on:
      - booking-api
  booking-api:
    build:
      dockerfile: Dockerfile
      context: ./booking-api
    restart: always
    ports:
      - "8888:8888"
    env_file: 
      - ./booking-api/.env
    volumes:
      - "/app/node_modules"
      - "./booking-api:/app"